cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    ? ''
    : 0
    a:
      email: rodrigo.garcia21111@gmail.com
      format:
      - '---'
      - Puntos clave
      - "Di\xE1logo"
      - Lista
      - Entrevista
      - "An\xE1lisis comparativo"
      - Tutorial
      - "Cr\xEDtica"
      - Resumen
      lan: 1
      name: Rodrigo
      password: $2b$12$lpwCn9UOuHIqIgprPni3KOIp.7.iqrxgCxjfO7bUgNCNy3h/O./MS
      style:
      - "Humor\xEDstico"
      - Amistoso
      - "Acad\xE9mico"
      - Convincente
      - Profesional
      - Mostro
    b:
      email: asd@algo
      lan: 1
      name: Bob
      password: $2b$12$6BuA4oAQRFm369WCy5TobOcG6E8oc3m0ycjduVX7YHbFHC4oWVE2a
      style:
      - '---'
      - Desenfadado
      - Informativo
      - Persuasivo
      - "Humor\xEDstico"
      - Amistoso
      - "Acad\xE9mico"
      - Convincente
      - Profesional
      - "Po\xE9tico"
preauthorized:
  emails:
  - melsby@gmail.com
